# Generated by Django 4.2.23 on 2025-07-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_alter_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zip_code_w_id',
            field=models.ForeignKey(blank=True, db_column='wCodeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zip', to='location.location'),
        ),
    ]
